### PR TITLE
Cache get_autoscaling_group_name

### PR DESCRIPTION
**Pull request by DeviaVir**
Caches get_autoscaling_group_name for a day (if I understood [@FileCache](https://pypi.python.org/pypi/filecache) correctly)

This PR has cross-dependency with [this PR](https://github.com/pebble/docker-cloudwatch-stats/pull/2).

@lrvick

### CODE REVIEW

**Comment by DeviaVir** [comment]
This should resolve our throttling issues on AWS.

**Comment by DeviaVir** [comment]
If this solution turns out bogus, we can try using describe instances for getting tags: http://stackoverflow.com/questions/19516678/obtaining-tags-from-aws-instances-with-boto
perhaps that limit is higher.

**Comment by thepwagner** [comment]
Maybe just fold https://github.com/pebble/docker-cloudwatch-stats/blob/master/Dockerfile into this repo?

**Comment by thepwagner** [comment]
Where does the FileCache get stored? (We want to make that a VOLUME?)

**Pull request closed without merging**
